[package]
name = "keyprod"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
async-trait = "0.1.89"
chrono = "0.4.42"
env_logger = "0.11.10"
lexopt = "0.3.1"
libc = "0.2.174"
libudev = "0.3.0"
log = "0.4.29"
nix = { version = "0.30.1", features = ["event"] }
rusqlite = "0.37.0"
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = ["rt", "sync", "macros", "time"] }

[build-dependencies]
bindgen = "0.72.0"
prettyplease = "0.2.37"
quote = "1.0.41"
syn = { version = "2.0.106", features = ["parsing"] }

[dev-dependencies]
mockall = "0.13.1"
