use chrono::NaiveDate;

use crate::plugins::history::PluginHistoryConfig;

const PLUGIN_NAME: &str = "Stat";

pub struct PluginStat {
    format: PluginStatFormat,
    db_path: std::path::PathBuf,
}

#[derive(thiserror::Error, Debug)]
pub enum Error {
    #[error("{0}")]
    Db(#[from] rusqlite::Error),
    #[error("{0}")]
    Io(#[from] std::io::Error),
    #[error("{0}")]
    Plot(#[from] PlotError),
}

#[derive(thiserror::Error, Debug)]
#[error(transparent)]
pub struct PlotError(#[from] Box<dyn std::error::Error + Send + Sync>);

pub type Result<T, E = Error> = std::result::Result<T, E>;

#[derive(Clone, Default)]
pub struct PluginStatConfig {
    format: PluginStatFormat,
    db_path: Option<std::path::PathBuf>,
    // TODO: choose date (single day, month, year, period, etc)
}

#[derive(Clone, Default)]
pub enum PluginStatFormat {
    #[default]
    Csv,
}

pub struct PluginStatFactory;

impl PluginStat {
    pub fn init(config: PluginStatConfig) -> Result<Self> {
        let db_path = config.db_path.unwrap_or_else(Self::get_default_db_path);

        Ok(Self {
            format: config.format,
            db_path,
        })
    }

    fn get_default_db_path() -> std::path::PathBuf {
        PluginHistoryConfig::get_default_db_path()
    }
}

#[async_trait::async_trait]
impl super::Plugin for PluginStat {
    fn name(&self) -> &'static str {
        PLUGIN_NAME
    }

    async fn run(&mut self, mut _rx: tokio::sync::mpsc::Receiver<crate::Event>) {
        match &self.format {
            PluginStatFormat::Csv => {
                match CsvStatPrinter::new(&self.db_path) {
                    Ok(stats) => stats.print_stdout(),
                    Err(err) => {
                        log::error!("Failed to collect statistics from the database: {err}");
                    }
                };
            }
        }

        log::info!("{} finished it's work.", self.name());
    }
}

impl super::PluginConfig for PluginStatConfig {
    fn name(&self) -> &'static str {
        PLUGIN_NAME
    }

    fn try_init_plugin(
        self: Box<Self>,
    ) -> std::result::Result<Box<dyn super::Plugin>, Box<dyn std::error::Error + Send + Sync>> {
        match PluginStat::init(*self) {
            Ok(pl) => Ok(Box::new(pl)),
            Err(err) => Err(Box::new(err)),
        }
    }
}

impl super::PluginFactory for PluginStatFactory {
    fn cli_name(&self) -> &'static str {
        "stat"
    }

    fn help(&self) -> String {
        "\
Provides a convenient interface for getting information from the database generated by the
\"history\" plugin.
Options:
    --csv
        Prints information in csv format: <date>,<keystrokes>
        [default]

    --db-path <path>
        By default it tries to connect to a default database. This can be overwritten with this
        option if you need to specify which database to use.
        [default: see \"history\":\"--db-path\"]
"
        .to_string()
    }

    fn parse_args(
        &self,
        parser: &mut lexopt::Parser,
    ) -> std::result::Result<Box<dyn super::PluginConfig>, lexopt::Error> {
        use lexopt::prelude::*;

        let mut config = PluginStatConfig::default();

        while let Some(arg) = parser.next()? {
            match arg {
                Long("csv") => config.format = PluginStatFormat::Csv,
                Long("db-path") => config.db_path = Some(parser.value()?.parse()?),
                _ => return Err(arg.unexpected()),
            }
        }

        Ok(Box::new(config))
    }
}

#[derive(Debug, Clone, Copy)]
struct StatRecord {
    date: chrono::NaiveDate,
    count: u64,
}

#[derive(Debug, Clone)]
struct StatCollector {
    stats: Vec<StatRecord>,
}

impl StatCollector {
    pub fn read(db_path: &std::path::Path) -> Result<Self> {
        let conn = rusqlite::Connection::open_with_flags(
            db_path,
            rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY,
        )?;

        let mut stmt = conn.prepare("SELECT Date, KeypressCnt FROM Statistics")?;
        let stats = stmt
            .query_map([], |row| {
                Ok(StatRecord {
                    date: NaiveDate::parse_from_str(&row.get::<usize, String>(0)?, "%F").map_err(
                        |e| {
                            rusqlite::Error::FromSqlConversionFailure(
                                1,
                                rusqlite::types::Type::Text,
                                Box::new(e),
                            )
                        },
                    )?,
                    count: row.get(1)?,
                })
            })?
            .collect::<Result<Vec<StatRecord>, rusqlite::Error>>()?;

        Ok(Self { stats })
    }

    fn get_all_records(&self) -> &[StatRecord] {
        &self.stats
    }
}

struct CsvStatPrinter {
    stats: StatCollector,
}

impl CsvStatPrinter {
    pub fn new(db_path: &std::path::Path) -> Result<Self> {
        let stats = StatCollector::read(db_path)?;

        Ok(Self { stats })
    }

    pub fn print_stdout(&self) {
        for record in self.stats.get_all_records() {
            println!("{},{}", record.date, record.count);
        }
    }
}
